INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE)
VALUES (RANDOM_UUID(), 'Jhon', 'courses/Java', 500);
INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE)
VALUES (RANDOM_UUID(), 'Michael', 'courses/Java', 500);
INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE)
VALUES (RANDOM_UUID(), 'Peter', 'courses/Java', 500);
INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE)
VALUES (RANDOM_UUID(), 'Sebastian', 'courses/Java', 500);
INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE)
VALUES (RANDOM_UUID(), 'Aaron', 'courses/Java', 500);
INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE)
VALUES (RANDOM_UUID(), 'William', 'courses/Java', 500);
INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE)
VALUES (RANDOM_UUID(), 'a6ffa219-1fa9-4456-8cc5-c5c78325fa42', 'courses/Java', 500);
INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE)
VALUES (RANDOM_UUID(), 'a6ffa219-1fa9-4456-8cc5-c5c78325fa42', 'courses2/Java', 1000);